### ISSUE TITLE
Unable to override Jest's testEnvironment

### ISSUE THREAD

**Issue by 0b10** [sharegate/craco#108]
##### #1

```js
module.exports = {
  plugins: [
    {
      plugin: {
        overrideJestConfig: ({ jestConfig }) => {
          jestConfig.testEnvironment = "jest-environment-jsdom-fifteen";
          return jestConfig;
        }
      }
    }
  ]
};
```
output: 

> npm run test -- --showConfig | grep -iE 'testEnvironment"' "testEnvironment": "\<rootDir\>/node_modules/jest-environment-jsdom/build/index.js",

#### #2

```js
module.exports = {
  jest: {
    configure: jestConfig => {
      jestConfig.testEnvironment = "jest-environment-jsdom-fifteen";
      return jestConfig;
    }
  }
};
```

output: 

> npm run test -- --showConfig | grep -iE 'testEnvironment"' "testEnvironment": "\<rootDir\>/node_modules/jest-environment-jsdom/build/index.js",

The override is run in both cases, but the desired result is not achieved

**Comment by patricklafrance** [comment]
Hi @0b10,

This is quite hard to override with CRACO because CRA override the `testEnvironment` by specifying the CLI argument `--env` and ignore the value specified in the Jest config.

I am not sure why it's done this way, it's seems pretty inconsistant.. Anyway there is not much I can do about it.

If you find a way and you want to submit a PR, I will gladly review and merge it if appropriate.

In the meantime, I suggest you specify you're Jest environment this way:

```bash
"test": "craco test --env jsdom-fifteen",
```

Thank you,

Patrick
