### ISSUE TITLE
Use with Storybook

### ISSUE THREAD

**Issue by jgoux** [sharegate/craco#43]
Hello,

according to Storybook, it's possible to use our own webpack.config.js (https://storybook.js.org/configurations/custom-webpack-config/#using-your-existing-config) to configure Storybook as well.

How would you wire Storybook and craco to use the same configuration?

The most simple would be to provide the function which computes the craco config into the webpack config?

Something like :
```js
// .storybook/webpack.config.js
const { craco } = require('@craco/craco')
module.exports = craco(require('../craco.config.js'))
```

**Comment by patricklafrance** [comment]
Hi @jgoux 

craco doesn't return any config.

The way it works is that it make some tweaking according to how craco si setup and then call CRA.

Maybe you could use the plugin system of craco to write a plugin that will output the webpack config somewhere accessible to storybook. I am not sure it will be easy thought because CRA webpack config have a lot of required dependent files.

**Comment by jgoux** [comment]
Thanks for your answer @patricklafrance 

I wish the ecosystem was more collaborative about webpack's config overwrite.

Project such as https://github.com/andywer/webpack-blocks would be a good start, then craco or storybook's configs could be just a thin layer over this primitive.

Have a nice day! 🌞

**Comment by patricklafrance** [comment]
I know it's been a while but it should work now with the new API.

Documentation available [here](https://github.com/sharegate/craco/blob/master/packages/craco/README.md#api).

**Comment by gajus** [comment]
@patricklafrance shouldn't that example be:

```js
/* eslint-disable import/first */

const {
  createWebpackDevConfig,
} = require('@craco/craco');
const cracoConfig = require('../craco.config.js');

module.exports = (webpackConfig) => {
  const config = createWebpackDevConfig({
    ...cracoConfig,
    webpack: {
      configure: webpackConfig.config,
    },
  });

  return config;
};


```

?

**Comment by patricklafrance** [comment]
Hi @gajus 

Did you have problems with the original exemple?

Storybook support "full control mode" for the webpack config so I thought that would be enough. A merge might be necessary.

Not sure about the `webpack` key in your example though.

Patrick

**Comment by gajus** [comment]
I didn't manage to get it working with either your approach or my approach. With your approach webpack was bundling the main application, not Storybook. With my approach I started getting loads of Babel errors (cannot recall what they were now).

I ended up just patching webpack config injected by Storybook:

```js
/* eslint-disable import/first */

module.exports = ({ config }) => {
  const babelLoaderOptions = config.module.rules[0].use[0].options;

  config.module.rules = config.module.rules.filter((rule) => {
    return !(rule.use && rule.use[0].loader && rule.use[0].loader.includes('eslint-loader'));
  });

  // The last rule is the rule added by Storybook to pre-process project files.
  const babelRule = config.module.rules[config.module.rules.length - 1];

  if (!babelRule.loader.includes('babel-loader')) {
    throw new Error('Unexpected state.');
  }

  babelRule.options.plugins = [
    [
      'babel-plugin-styled-components',
      {
        diplayName: true,
      },
    ],
    ...babelRule.options.plugins,
  ];

  config.module.rules.push({
    test: /\.stories\.js?$/,
    loaders: [
      {
        loader: require.resolve('@storybook/addon-storysource/loader'),
        options: {
          parser: 'flow',
        },
      },
    ],
    enforce: 'pre',
  });

  return config;
};

```

**Comment by patricklafrance** [comment]
ok thank you, thank you for your feedback, I will remove the example and revisit it later

**Comment by liokm** [comment]
Simply merge seems not work. With the help of `preset-create-react-app` it could work. I have raised an issue here https://github.com/storybookjs/presets/issues/109

**Comment by danielknell** [comment]
I hit problems with Craco and storybook last night so built an experimental preset based on preset-create-react-app to use the webpack  config from Craco instead of pulling it directly from react-scripts.

This means any Craco plugins, changes postcss plugins, manual webkit tweaks, etc will also be applied to storybook.

Its a bit hackey at the moment and calls out to internal apis inside preset-create-react-app but that seemed like a better choice than re-inventing the wheel. 

Any feedback, contributions, fixes, etc are welcome, it would be good to have solid integration between storybook and Craco.

* [Github Repo](https://github.com/artisanofcode/storybook-preset-craco)
* [Yarn](https://yarnpkg.com/package/storybook-preset-craco)
* [NPM](https://www.npmjs.com/package/storybook-preset-craco)
