### ISSUE TITLE
Fix spacing issue with our prettier settings

### ISSUE THREAD

**Issue by patricklafrance** [sharegate/craco#8]
It seems like there is a problem with the prettier configuration: #4

**Comment by ndbroadbent** [comment]
Hi, I just found this issue! I was actually wondering where the `printWidth: 5000` option came from. Was that added intentionally, or was the `.prettierrc` copied from a different project? I'm really curious to know why `5,000` was chosen for this setting. Thanks!

**Comment by lydell** [comment]
https://prettier.io/docs/en/options.html#print-width

> **For readability we recommend against using more than 80 characters:**
>
> In code styleguides, maximum line length rules are often set to 100 or 120. However, when humans write code, they don't strive to reach the maximum number of columns on every line. Developers often use whitespace to break up long lines for readability. In practice, the average line length often ends up well below the maximum.
>
> Prettier, on the other hand, strives to fit the most code into every line. With the print width set to 120, prettier may produce overly compact, or otherwise undesirable code.
>
> See the [print width rationale](https://prettier.io/docs/en/rationale.html#print-width) for more information.

**Comment by patricklafrance** [comment]
Merged #19 to set the print-width to 80. However, this was not the problem of this issue.

This issue is about investigating why cj had whitespaces added to every lines of his PR when using this repo toolings. Than being said, you didn't seem to have those issues or your PR @ndbroadbent.

**Comment by ndbroadbent** [comment]
@patricklafrance Oh I see, yes I did actually have that as well. I had to manually select the relevant changes. This can be solved by running Prettier on all the files and then committing the whitespace/formatting changes. I can do that now and send another PR

**Comment by ndbroadbent** [comment]
Oh actually this was a line-ending issue. The codebase has `CRLF` line endings (`\r\n`), and Prettier is formatting files with `LF` line endings (`\n`). So I think is actually a Windows vs. Mac/Linux issue. 

I found some Prettier issues about that: 

* [#92 - Prettier change all line break to LF](https://github.com/prettier/prettier/issues/92)
* [#5320 - An option to enforce certain line endings (LF / CRLF)](https://github.com/prettier/prettier/issues/5320)
* [#537 - https://github.com/prettier/prettier/issues/537](https://github.com/prettier/prettier/issues/537)

This is very confusing.

[This comment](https://github.com/prettier/prettier/issues/92#issuecomment-397421739) doesn't seem to be true anymore:

> @cphoover prettier will respect the first end of line it sees. If it's a \r\n it's going to replace all the others with \r\n and same for \n.

Because I just ran `prettier --write **/*.js`, and it replaced all the line endings. I will open another issue on Prettier.

In the meantime, maybe you could add the suggestion from [#5320](https://github.com/prettier/prettier/issues/5320) to the contributing instructions in the README:

* Run `git config --global core.autocrlf true` to use `CRLF` line endings

I just ran:

```
$ git config --global core.autocrlf true
$ prettier --write **/*.js
```

And now Prettier is using the correct line endings.

(I think most JavaScript developers use `LF` line endings. But up to you!)

**Comment by ndbroadbent** [comment]
Also I forgot to respond to your comment about the width:

> It's intentional, since we have pretty large screens at Sharegate I usually prefer a high width instead of taking more spaces top to bottom.

That's fine for me as well! I wouldn't mind if you wanted to set `printWidth` to something like 100 or 150. But setting it to 5,000 caused the formatting problems, because Prettier will never print code on multiple lines if it can all fit on a single line.

**Comment by patricklafrance** [comment]
Fix with the following commit https://github.com/sharegate/craco/commit/3e709c6ebdc308e99e01b963732a43e29fddfb79

In short:

- Added a few tools to enforce CRLF
- Added ESLint linebreak-style
- Added husky + lint-staged to run prettier when files are staged
- prettier should read .editorconfig "end_of_line" key  in the next release: https://github.com/prettier/prettier/pull/5327

**Comment by lydell** [comment]
Prettier should already read "end_of_line" in .editorconfig since 1.15.0.

**Comment by ndbroadbent** [comment]
@patricklafrance Awesome, thanks! This should make it much easier for other people to start contributing. I also prefer the 120 chars `printWidth`, that looks better on my screen as well.

**Comment by patricklafrance** [comment]
@lydell according to this PR https://github.com/prettier/prettier/pull/5327 it was merged 7 days ago. 

I haven't test it thought.

**Comment by patricklafrance** [comment]
@lydell I should have read the release notes of 1.15.0, you're right the PR made it to 1.15.0!
